// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24_q3lba9VT0D6CbjrwflYSbZEom0nw0',
    appId: '1:454541959049:web:6511533fde8124be1e4b58',
    messagingSenderId: '454541959049',
    projectId: 'marvel-env',
    authDomain: 'marvel-env.firebaseapp.com',
    databaseURL: 'https://marvel-env-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-env.appspot.com',
    measurementId: 'G-J5BEK913B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvi4hJXlY0hUAY2xmnV2JW5ngDY2wED5M',
    appId: '1:454541959049:android:3620d633e81532851e4b58',
    messagingSenderId: '454541959049',
    projectId: 'marvel-env',
    databaseURL: 'https://marvel-env-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-env.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDe5ipKM8MOVR-uXa9CuPv4XwZ8CwkON8',
    appId: '1:454541959049:ios:0e2f82aa4e9d02491e4b58',
    messagingSenderId: '454541959049',
    projectId: 'marvel-env',
    databaseURL: 'https://marvel-env-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-env.appspot.com',
    iosBundleId: 'com.example.flutterPokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDe5ipKM8MOVR-uXa9CuPv4XwZ8CwkON8',
    appId: '1:454541959049:ios:0e2f82aa4e9d02491e4b58',
    messagingSenderId: '454541959049',
    projectId: 'marvel-env',
    databaseURL: 'https://marvel-env-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-env.appspot.com',
    iosBundleId: 'com.example.flutterPokedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA24_q3lba9VT0D6CbjrwflYSbZEom0nw0',
    appId: '1:454541959049:web:d80d94140ab5b4ce1e4b58',
    messagingSenderId: '454541959049',
    projectId: 'marvel-env',
    authDomain: 'marvel-env.firebaseapp.com',
    databaseURL: 'https://marvel-env-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-env.appspot.com',
    measurementId: 'G-3631R517Q2',
  );
}
